dist: bionic
language: node_js
node_js: 14.4
install:
  - npm install -g typescript@3.9.5
  - npm install -g codecov@3.7.0
  - npm ci
script:
  - gulp lint-check
  - gulp build
  - gulp coverage
after_success:
  - gulp coverage-report
