dist: bionic
language: node_js
node_js: 14.4
install:
  - npm install -g typescript
  - npm install -g codecov
  - npm ci
  - gulp build
script:
  - gulp build
  - gulp coverage
after_success:
  - gulp coverage-report
